DataScienceSpecialization/DataScienceSpecialization.github.io

- rprog.md
add a cheatsheet for R covering all lectures
> r language cheatsheet

- other.md
I have created a vagrant based solution which provides RStudio server plus GitHub setup, giving user a complete environment for R based experiments, without the need to install all the necessary stuff locally, and I think it's worth sharing.
> Added Virtual machine with RStudio server and github setup in other resources

- curated.md
Hi,
I've added a link to Data Science Ontology, which I believe will assist fellow learners on learning data science concepts. I've also corrected some typos.
Cheers,
Yoke
> Added link and corrected typos

- rprog.md
- toolbox.md
The following two links are rather useful for git and R beginners. Please consider merging.
> Add try git and try r links

- curated.md
Adding the references of very good video tutorials available out there
to learn R.
> Add Google Developers R Programming Video Lectures

- rprog.md
`testthat` unit tests for R Programming Coursera course Assignment 3.
> Please add pa3test to the repository.

- curated.md
I have been collecting these data science resources for 2+ years. Will like to share them with the community. It has free learning resources for R, data science, visualization, data comics and much more. https://trello.com/b/rbpEfMld/data-science
> Trello Board Collection of Data Science Resources

- curated.md
Diving Into Data Science Flipboard, collection of data science related articles, news and materials: https://flipboard.com/@thiakx/diving-into-data-science-5823ectuy
> Diving Into Data Science Flipboard

- pml.md
I think this page fits pretty well with the content of the PML course. Let me know if you have any questions... thanks!
> add comparison of supervised learning algorithms to PML page

- Interactive_Git_Game
- curated.md
The two links below are for an interactive fun game to learn Git! It was created by GitHub user "pcottle" (check him out). None of this work is mine, I am simply sharing with you for learning purposes.
>  Interactive_Git_Game

- getclean.md
I contributed the following entry to the Getting and Cleaning Data section:
Pre-processing Excel files before loading them into R
> Contributing an entry to Getting and Cleaning Data

- statinf-exp-distro
Births data set from CDC, US for analysis of exponential distribution. Hope it is helpful for Course Project for 'Statistical Inference' course.
>  Inter-arrival times of births for exponential distribution.

- Codebook template.Rmd
Codebook template that can be used in the Getting and Cleaning data
project.
> codebook template

- about.md
- ddp.md
- eda.md
- getclean.md
- pml.md
- regmod.md
- repres.md
- rprog.md
- statinf.md
- toolbox.md
I added links to the set of notes I compiled using RMarkdown. There has been a good amount of positive response so I thought I should share it on the community site
> Added links to the notes I compiled for all 9 classes

- pml.md
Hello! Although this video is part of my series on machine learning using Python, this particular video actually has nothing to do with Python, and focuses instead on explaining machine learning at a conceptual level.
Let me know if you have any questions.... thanks!
> add link to machine learning video on PML page

- statinf.md
> Add link to Probability and Statistics Cookbook

- toolbox.md
I've created a blog post about the basic commands in the bash terminal. I hope it adds value to the repository.
> add link to post about how to use bash commands

- rprog.md
I've written this step-by-step tutorial to help who struggles in understanding the instructions of Programming Assignment 2. It gives examples of the new concepts introduced in the instructions for people not familiar with R or programming in general.
> Tutorial for those struggling with PA2

- rprog.md
I have made a quick tutorial with simplified functions to manage small data frame that should give insights on how to manage bigger datas like the hospital csv
> Tutorial for those struggling with PA3

- curated.md
Many of my favourite bookmarks are included here. They include contributions from students in the Toolbox class.
> Added a number of links to Curated page

- rprog.md
Not sure if the DSS Community Site is the best place for this or not.  I made a few small changes to the submit script for R Programming PA1 (rprog-scripts-submitscript1.R).  Changes allow submitting multiple parts all at once and prompts the user if they want to submit another part before exiting.  Makes it much more convenient than calling submit() 10 times and going through all the prompts again and again.
> Added link to rprog.md for alternative submit script

- curated.md
Add way to save R files online, it's nice to shared R files
> Added link to save R files online in curated.md

- ddp.md
The Tutorial is an interactive R Markdown document, currently hosted on shinyapps.io.  It aims to take the reader step-by-step through the construction of a reasonably full-featured simulation app that lets statistics students explore, through simulation, the coverage properties of the classical t-intervals for a population mean.  After completing the tutorial the reader will be able to write his/her own simulation apps---hopefully having been spared some of the struggle that I went through when I first learned Shiny in the Spring of 2014.
> add link to Shiny simulation tutorial

- curated.md
This book is very well explained, and provides the basic understanding to build R packages.
http://r-pkgs.had.co.nz/
> add link to Hadley online book: R Packages

- other.md
I have included three blog post of how to use Shiny with Docker to share and deploy Shiny Apps easily.
> Including resources of how to share and deploy Shiny Apps with Docker

- getclean.md
This is my collected advice from 18 months of CTAing Getting and Cleaning Data
> Added David Hood advice for the course

- curated.md
This website contains lots of useful material about reproducible research.
> Added link to http://reproducibleresearch.net/

- statinf.md
After reading a few articles about the "reproducibility crisis" in scientific journals and the pervasive misinterpretation of p-values and confidence intervals, I had a moment of doubt about my own understanding of what you can and can't say with classical statistics. I made a little app using RStudio's manipulate package that helped me better understand the correct interpretation of confidence intervals by actually looking at 100 confidence intervals from resamples of a population with specified parameters.  I hope it helps others as well.
> Interactive Confidence Interval  Vizualization

- statinf.md
Add a short article discussing optimal sample size, supporting the week 4 Power Calculations lecture.
> Power calculations - optimal sample size article

- rprog.md
Content developed during May 2016 run of R Programming.
> Add article on R Onboarding for SAS Users

- rprog.md
> Add article on forms of the Extract Operator

- pml.md
- rprog.md
…within the Combining Predictors lecture, since it's been raised in two of the four most recent runs of the PML course.  Also added a couple of articles in R programming related to the pollutantmean() component of the first programming assignment.
> Added article explaining use of binomial theorem

- statinf.md
...illustrating how the probability value of the test statistic changes under two scenarios.
> Add article on permutation tests

- rprog.md
Add url for a step by step explanation of the code for the lexical scoping assignment.
> Add url for Demystifying makeVector() article.

- other.md
- rprog.md
Updated other.md to include link on HTTP/HTTPS proxy configuration guide
> Added proxy configuration guide

- statinf.md
Add the missing dash between first two rows of bullet list
> Add missing dash in bullet list

- eda.md
- getclean.md
I created a pdf file which might be benficial to students taking the Getting and Cleaning data course.  I pinned it to discussion forum and have gotten a few positive remarks. One of the old mentors of the course suggested i make a pull request to include the material to this repository. Hope you find it worthwhile and useful. Thanks.
> added link to my pdf file

- about.md
- eda.md
@seankross  added a new presentation and hope you don't mind if i added my names as a community contributor
@rdpeng created a presentation based on your presentation in EDA course
> metricsgraphic tutorial

- ddp.md
hi,
I created a project that has a lot of example plots using leaflet. I thought it might be worthwhile for some of the students in this course to take a look.
> adding a leaflet plot example
